from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

from _common import ROOT, load_json

REPORT_MD = ROOT / 'reports/repeatability_report.md'
REPORT_CSV = ROOT / 'reports/repeatability_report.csv'

GROUP_RULES = {
    'row1-memory-core': {'required_valid_runs': 2, 'policy': 'required'},
    'row2-memory-lancedb': {'required_valid_runs': 2, 'policy': 'recommended'},
    'row3-openviking-minus-core': {'required_valid_runs': 2, 'policy': 'required'},
    'row4-compat-primary': {'required_valid_runs': 1, 'policy': 'optional'},
}



def valid_full_runs(group: str) -> list[tuple[Path, dict[str, Any]]]:
    items = []
    for path in sorted(ROOT.glob(f'runs/full/*/{group}/run_summary.json'), key=lambda p: p.stat().st_mtime, reverse=True):
        data = load_json(path)
        if data.get('pipeline_status') == 'valid':
            items.append((path, data))
    return items



def pct_delta(new: float | int | None, old: float | int | None) -> str:
    if new is None or old in (None, 0):
        return ''
    return f'{((new - old) / old):+.2%}'



def pp_delta(new: float | None, old: float | None) -> str:
    if new is None or old is None:
        return ''
    return f'{((new - old) * 100):+.2f}pp'



def main() -> None:
    rows = []
    md_lines = [
        '# Repeatability Report',
        '',
        '> Auto-generated by `python3 scripts/build_repeatability_report.py`.',
        '',
        '| group | policy | valid_full_runs | requirement_met | latest_run | previous_run | completion_delta | qa_token_delta | pipeline_token_delta | notes |',
        '|---|---|---:|---|---|---|---:|---:|---:|---|',
    ]

    for group, rule in GROUP_RULES.items():
        runs = valid_full_runs(group)
        latest = runs[0][1] if runs else None
        previous = runs[1][1] if len(runs) > 1 else None
        requirement_met = len(runs) >= rule['required_valid_runs']
        notes = []
        if rule['policy'] == 'optional':
            notes.append('compatibility track; extra repeatability runs are optional and not part of strict stability criteria')
        elif rule['policy'] == 'recommended' and len(runs) < 2:
            notes.append('second valid full run is recommended by the plan but not mandatory for strict claim gating')
        elif rule['policy'] == 'required' and len(runs) < 2:
            notes.append('plan requires a second valid full run before stability can be claimed')
        if latest and previous:
            notes.append('latest two valid runs compared below')

        row = {
            'group': group,
            'policy': rule['policy'],
            'valid_full_runs': len(runs),
            'requirement_met': requirement_met,
            'latest_run': latest.get('run_id') if latest else '',
            'previous_run': previous.get('run_id') if previous else '',
            'completion_delta': pp_delta(latest.get('completion_rate') if latest else None, previous.get('completion_rate') if previous else None),
            'qa_token_delta': pct_delta(latest.get('qa_input_tokens_total') if latest else None, previous.get('qa_input_tokens_total') if previous else None),
            'pipeline_token_delta': pct_delta(latest.get('visible_pipeline_input_tokens_total') if latest else None, previous.get('visible_pipeline_input_tokens_total') if previous else None),
            'notes': '; '.join(notes),
        }
        rows.append(row)
        md_lines.append('| {group} | {policy} | {valid_full_runs} | {requirement_met} | {latest_run} | {previous_run} | {completion_delta} | {qa_token_delta} | {pipeline_token_delta} | {notes} |'.format(**row))

    with REPORT_CSV.open('w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    REPORT_MD.write_text('\n'.join(md_lines) + '\n', encoding='utf-8')
    print(f'Wrote {REPORT_CSV} and {REPORT_MD}')


if __name__ == '__main__':
    main()
