from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path
from typing import Any

from _common import ROOT

INPUT_DIR = ROOT / 'reports/manual_audit_samples'
OUT_MD = ROOT / 'reports/manual_audit_summary.md'
OUT_CSV = ROOT / 'reports/manual_audit_summary.csv'



def normalize(value: str) -> str:
    raw = (value or '').strip().lower()
    mapping = {
        'correct': 'correct',
        'true': 'correct',
        '1': 'correct',
        'wrong': 'wrong',
        'false': 'wrong',
        '0': 'wrong',
    }
    return mapping.get(raw, '')



def main() -> None:
    rows: list[dict[str, Any]] = []
    details: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for path in sorted(INPUT_DIR.glob('*.csv')):
        with path.open('r', encoding='utf-8', newline='') as f:
            reader = csv.DictReader(f)
            items = list(reader)
        if not items:
            continue
        group = items[0].get('group', path.stem)
        run_id = items[0].get('run_id', '')
        completed = [item for item in items if normalize(item.get('human_result', ''))]
        agree = 0
        disagree = 0
        disagreement_examples = []
        for item in completed:
            judge = normalize(item.get('judge_result', ''))
            human = normalize(item.get('human_result', ''))
            if judge == human:
                agree += 1
            else:
                disagree += 1
                reason = (item.get('disagreement_reason') or '').strip()
                disagreement_examples.append(reason or 'unspecified')
                details[group].append(item)
        audited = len(completed)
        agreement_rate = (agree / audited) if audited else None
        row = {
            'group': group,
            'run_id': run_id,
            'audited_cases': audited,
            'agree': agree,
            'disagree': disagree,
            'agreement_rate': f'{agreement_rate:.2%}' if agreement_rate is not None else '',
            'systematic_issue': 'pending-human-note' if disagreement_examples else '',
            'note': f'source={path.relative_to(ROOT)}',
        }
        rows.append(row)

    md_lines = [
        '# Manual Audit Summary',
        '',
        '> Auto-generated by `python3 scripts/summarize_manual_audit.py` from completed CSV workbooks under `reports/manual_audit_samples/`.',
        '',
        '| group | run_id | audited_cases | agree | disagree | agreement_rate | systematic_issue | note |',
        '|---|---|---:|---:|---:|---:|---|---|',
    ]
    for row in rows:
        md_lines.append('| {group} | {run_id} | {audited_cases} | {agree} | {disagree} | {agreement_rate} | {systematic_issue} | {note} |'.format(**row))

    with OUT_CSV.open('w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()) if rows else ['group', 'run_id', 'audited_cases', 'agree', 'disagree', 'agreement_rate', 'systematic_issue', 'note'])
        writer.writeheader()
        if rows:
            writer.writerows(rows)
    OUT_MD.write_text('\n'.join(md_lines) + '\n', encoding='utf-8')
    print(f'Wrote {OUT_CSV} and {OUT_MD}')


if __name__ == '__main__':
    main()
